name: euroscipy-2022-jupyterlite-emscripten-forge
channels:
- conda-forge
dependencies:
- python=3.10
- mamba
- pydata-sphinx-theme
- myst-parser
- empack
- bqplot==0.12.34
- ipycanvas==0.13.0
- ipyevents==2.0.1
- ipydatagrid==1.1.12
- ipyleaflet==0.17.1
- ipympl==0.8.2
- ipywidgets==7.7
- jupyterlab==3.4.5
- jupyterlab-language-pack-fr-FR
- jupyterlab-language-pack-zh-CN
- jupyterlab-fasta>=3,<4
- jupyterlab-geojson>=3,<4
- jupyterlab-tour==3.1.4
- jupyterlab-night
- plotly==5.10.0
- sympy==1.9
- pip:
  - jupyterlite-sphinx==0.7.1
  - jupyterlite-xeus-python==0.5.5
  - jupyterlite==0.1.0b12
  - jupyterlite-xeus-sqlite==0.2.1
